[2021-01-11 18:27:02,792] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.tesla_price_analyzer 2021-01-12T02:26:54.057549+00:00 [queued]>
[2021-01-11 18:27:02,798] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: MarketVol.tesla_price_analyzer 2021-01-12T02:26:54.057549+00:00 [queued]>
[2021-01-11 18:27:02,798] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-11 18:27:02,798] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-11 18:27:02,799] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-11 18:27:02,806] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): tesla_price_analyzer> on 2021-01-12T02:26:54.057549+00:00
[2021-01-11 18:27:02,808] {standard_task_runner.py:51} INFO - Started process 56205 to run task
[2021-01-11 18:27:02,814] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'MarketVol', 'tesla_price_analyzer', '2021-01-12T02:26:54.057549+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stock_dags.py', '--cfg-path', '/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/tmpwyp2ccif']
[2021-01-11 18:27:02,816] {standard_task_runner.py:76} INFO - Job 30: Subtask tesla_price_analyzer
[2021-01-11 18:27:02,847] {logging_mixin.py:103} INFO - Running <TaskInstance: MarketVol.tesla_price_analyzer 2021-01-12T02:26:54.057549+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-01-11 18:27:02,873] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=MarketVol
AIRFLOW_CTX_TASK_ID=tesla_price_analyzer
AIRFLOW_CTX_EXECUTION_DATE=2021-01-12T02:26:54.057549+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-12T02:26:54.057549+00:00
[2021-01-11 18:27:02,874] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T
[2021-01-11 18:27:02,875] {bash.py:158} INFO - Running command: python /Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py --symbol TSLA
[2021-01-11 18:27:02,882] {bash.py:169} INFO - Output:
[2021-01-11 18:27:03,307] {bash.py:173} INFO - /private/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/airflowtmpbn5b66mr/tmp/data/2021-01-11
[2021-01-11 18:27:03,310] {bash.py:173} INFO - Traceback (most recent call last):
[2021-01-11 18:27:03,310] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 35, in <module>
[2021-01-11 18:27:03,310] {bash.py:173} INFO -     main()
[2021-01-11 18:27:03,310] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 31, in main
[2021-01-11 18:27:03,311] {bash.py:173} INFO -     read_data(symbol)
[2021-01-11 18:27:03,311] {bash.py:173} INFO -   File "/Users/chowli/Documents/Springboard_DE/Projects/mini-projects/Airflow/marketvol/airflow/script/analyze.py", line 24, in read_data
[2021-01-11 18:27:03,311] {bash.py:173} INFO -     df = pd.read_csv(file)
[2021-01-11 18:27:03,312] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 605, in read_csv
[2021-01-11 18:27:03,312] {bash.py:173} INFO -     return _read(filepath_or_buffer, kwds)
[2021-01-11 18:27:03,312] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
[2021-01-11 18:27:03,312] {bash.py:173} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2021-01-11 18:27:03,313] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 814, in __init__
[2021-01-11 18:27:03,313] {bash.py:173} INFO -     self._engine = self._make_engine(self.engine)
[2021-01-11 18:27:03,313] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
[2021-01-11 18:27:03,314] {bash.py:173} INFO -     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
[2021-01-11 18:27:03,314] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1862, in __init__
[2021-01-11 18:27:03,314] {bash.py:173} INFO -     self._open_handles(src, kwds)
[2021-01-11 18:27:03,314] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/parsers.py", line 1363, in _open_handles
[2021-01-11 18:27:03,315] {bash.py:173} INFO -     storage_options=kwds.get("storage_options", None),
[2021-01-11 18:27:03,315] {bash.py:173} INFO -   File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/pandas/io/common.py", line 644, in get_handle
[2021-01-11 18:27:03,315] {bash.py:173} INFO -     newline="",
[2021-01-11 18:27:03,316] {bash.py:173} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/hy/5f75_vt15hb_bfkv9vvnx5sw0000gn/T/airflowtmpbn5b66mr/tmp/data/2021-01-11/TSLA.csv'
[2021-01-11 18:27:03,356] {bash.py:177} INFO - Command exited with return code 1
[2021-01-11 18:27:03,363] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/chowli/.local/share/virtualenvs/marketvol-WbDfdy4N/lib/python3.7/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-01-11 18:27:03,365] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=MarketVol, task_id=tesla_price_analyzer, execution_date=20210112T022654, start_date=20210112T022702, end_date=20210112T022703
[2021-01-11 18:27:03,425] {local_task_job.py:118} INFO - Task exited with return code 1
